# Generated by Django 3.2.7 on 2021-10-20 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pizza_size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='pizza_toppings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toppings', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='pizza_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='pizza_orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('pizza_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.pizza_size')),
                ('pizza_toppings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.pizza_toppings')),
                ('pizza_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.pizza_type')),
            ],
        ),
    ]
