# Generated by Django 3.2.7 on 2021-10-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza_orders',
            name='pizza_toppings',
        ),
        migrations.AddField(
            model_name='pizza_orders',
            name='pizza_toppings',
            field=models.ManyToManyField(to='testapp.pizza_toppings'),
        ),
    ]
