# Generated by Django 3.2.7 on 2021-10-20 11:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20211020_0357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza_orders',
            name='pizza_toppings',
        ),
        migrations.AddField(
            model_name='pizza_orders',
            name='pizza_toppings',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
